CREATE SCHEMA IF NOT EXISTS chatboot;

CREATE TABLE IF NOT EXISTS chatboot.users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
);